name: Auto Release Patch Version

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          # Fetch all tags
          git fetch --tags
          # Get the latest tag
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "Latest tag: $LATEST_TAG"
          # Increment the patch version
          NEW_TAG=$(echo $LATEST_TAG | awk -F. '{printf("%d.%d.%d", $1, $2, $3+1)}')
          echo "New tag: $NEW_TAG"
          # Set outputs for use in later steps
          echo "::set-output name=latest_tag::$LATEST_TAG"
          echo "::set-output name=new_tag::$NEW_TAG"

      - name: Create new tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag ${{ steps.get_tag.outputs.new_tag }}
          git push origin ${{ steps.get_tag.outputs.new_tag }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.new_tag }}
          release_name: Release ${{ steps.get_tag.outputs.new_tag }}
          draft: false
          prerelease: false