# Major: v1.2.3 → v2.0.0
# Minor: v1.2.3 → v1.3.0
# Patch: v1.2.3 → v1.2.4

name: Create Tag and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the new version (e.g., 2.0.5)"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate version format
        id: validate_version
        run: |
          version="${{ github.event.inputs.version }}"
          if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format. Use format: X.Y.Z (e.g., 2.0.5)"
            exit 1
          fi
          echo "new_tag=v$version" >> $GITHUB_ENV

      - name: Create new tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.new_tag }}
          name: Release ${{ env.new_tag }}
          draft: false
          prerelease: false
          body: "Manual release for version ${{ env.new_tag }}"

